### ISSUE TITLE
KeyError: 'poster' when trying to get recordings

### ISSUE THREAD

**Issue by siliwan** [Sholofly/lghorizon-python#23]
### Problem
Found through the [lghorizon](https://github.com/Sholofly/lghorizon) component for Homeassistant, it appears that when retrieving records the api returns some recordings that do not provide a poster image.

### Possible Solution
In the [models.py](https://github.com/Sholofly/lghorizon-python/blob/76bdeaad8d0b936c8fe7841f18ff0e357208d1f2/lghorizon/models.py#L191) file, check if the key "poster" exists, either defaulting to `None` or not set it over the constructor and rather afterwards like seasonNumber:

```python
if "poster" in recording_json and "url" in recording_json["poster"]:
    self.image =  recording_json["poster"]["url"]
```

### Trace

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1223, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lghorizon/media_player.py", line 358, in async_browse_media
    recordings = await self.hass.async_add_executor_job(self.api.get_recordings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lghorizon/lghorizon_api.py", line 435, in get_recordings
    recordings.append(LGHorizonRecordingSingle(recording_data_item))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lghorizon/models.py", line 202, in __init__
    recording_json["poster"]["url"],
    ~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'poster'
```

**Comment by Sholofly** [comment]
Fixed it in latest release
